### ISSUE TITLE
Ontology for EB vs. RB

### ISSUE THREAD

**Issue by djow2019** [SuLab/WikiGenomesBase#140]
Need a way to distinguish whether a protein is part of the EB or RB timing. 
Brenda Tissue IDs: BTO_0001172 and BTO_0000377

Need to find best way to get them in WikiData

@andrewsu

**Comment by djow2019** [comment]
Thinking of making a Brenda Ontology Annotations module.

From kevin: 
Here is some sample data for EB/RB annotation purposes. Pulled from PMID 22014092
CT288 (and CTL0540): EB enrichment
PmpD, CT812, CTL0183: RB enrichment
IncG, CT118, CTL0373: RB enrichment
OmcB, CT443, CTL0702: EB enrichment
For all 4 examples, you can push to all orthologs (please do)

**Comment by djow2019** [comment]
Waiting for "upregualted in" to be approved in WikiData.
https://www.wikidata.org/wiki/Wikidata:Property_proposal/Natural_science#upregulated_in

**Comment by khybiske** [comment]
@djow2019 @andrewsu Finally checking this off my to-do list... For the EB/RB data assignments (PMID 22014092 Table S1), I think we can set thresholds exactly as the authors did. They found 426 proteins expressed in EB, and 269 in RB (see Fig 3A). These proteins overlap. You can look at the Venn diagram (I will also paste below) to see how many are EB only, RB only, and both. Very easy to get these proteins (and GI IDs) from Table S1. If you filter columns G and H (separately) to exclude zero values, the spreadsheet displays the correct lists of 426 and 269 proteins.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/29986637/43490173-70a5d35e-94d4-11e8-9f6a-e6213c0f25c1.png">

**Comment by djow2019** [comment]
Updated the property proposal and changed upregulated in to expressed in. Hopefully this time we can get it approved! https://www.wikidata.org/wiki/Wikidata:Property_proposal/Natural_science#expressed_in
