### ISSUE TITLE
Rename HPI module to Protein Interactions

### ISSUE THREAD

**Issue by khybiske** [SuLab/WikiGenomesBase#145]
It just occurred to me that we also have instances of known chlamydia–chlamydia protein interactions. My recommendation is we rename this module to _**Protein Interactions**_ and add 2 subsections: Host-pathogen interactions (what we have now) 
and
Bacteria protein interactions (new). Same table as HPI, but change host to Bacteria (and lookups should go to the current Chlamydia genome).

**Comment by djow2019** [comment]
I think you mentioned you also had a spreadsheet of all the host pathogen interactions. Can you share it with me?

**Comment by djow2019** [comment]
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/db3b0022-b4e9-4cd3-8972-d2620c82d394)
