### ISSUE TITLE
show expression data for orthologs

### ISSUE THREAD

**Issue by putmantime** [SuLab/WikiGenomesBase#15]
Leaning towards showing expression timing for all orthologs in the expression timing box

**Comment by putmantime** [comment]
-Will incorporate expression timing data for D strain from different paper

**Comment by andrewsu** [comment]
Need to get data sources for other strains (from Dan?)

**Comment by khybiske** [comment]
Expression data for Ctr D comes from this study: 21051342. "Wonderful" example where the paper contains very little data for us to use. Scott happens to have their raw excel file. See attached. I think tab 4 best contains what we're after, but I'm checking with Scott.

[Belland array table.xlsx](https://github.com/SuLab/ChlamBase.org/files/1156648/Belland.array.table.xlsx)

**Comment by khybiske** [comment]
Tim, regarding the excel file for gene expression data. Scott says the last tab is the one we want to process.

**Comment by khybiske** [comment]
Wrong PMID reference for the C. trachomatis D expression data. It comes from here: 12815105

**Comment by putmantime** [comment]
This is great data, but if we are going to include it it we need to find consistent way to report it on ChlamBase.  The L2 data was binned to 'early' , 'mid', 'mid-late' etc.  
How dow we go about this for the DUW3 data?

**Comment by khybiske** [comment]
Hmm, let me chew on that and get back to you

**Comment by khybiske** [comment]
@putmantime My recommendation is that we do not try to harmonize the two data sets. I don't see how. Richard analyzed L2 at 6, 12, 18, 24, and 36 hpi. Harlan analyzed at 1, 3, 8, 16, 24, and 40 hpi. I suggest you keep the L2 data as they are, albeit with one minor change (**can you slide mid_late over the left, between mid and late?**). For the D data, go with:
- Constitutive
- Immediate early (1 h)
- Early (3 h)
- Mid (8 OR 16? boolean?)
- Mid_late (24 h)
- Late (40 h)

Do you think it's an issue to silo the data as specific for each strain?

**Comment by andrewsu** [comment]
oh, meant to chime in on this.  I agree with @khybiske's last comment -- I don't think it would be necessary or desirable to try to normalize each data set.  I'd use the labels that the authors used, and let the users of chlambase do whatever interpretation/alignment of those labels that they deem appropriate...

**Comment by putmantime** [comment]
Referenced by @khybiske in Issue #25 as well.  I think that the only challenge is that creating a visual like the existing one requires interpretation of the table and applying some sort of threshold.  Are we suggesting moving away from the distilled visualization model to essentially just mirroring the table from the pub?  If so it seems we need a way to present any table caption that explains the fields and their values in detail if it exists.  For the Caldwell D dataset https://www.ncbi.nlm.nih.gov/pmc/articles/PMC166254/bin/pnas_1331135100_index.html
there doesn't seem to be any caption explaining what the numbers mean.  I agree there is no way to harmonize, just noting that we are venturing into to displaying raw data, which we haven't really done before.

**Comment by andrewsu** [comment]
what about using something like this from the google charts api? https://developers.google.com/chart/interactive/docs/gallery/candlestickchart

**Comment by khybiske** [comment]
Ok, so I agree this is a little more challenging that I first thought. However arbitrarily, Stephens at least classified expression patterns into naming classes that we could copy. Caldwell just has numeric values, and inferring from how the paper discusses genes defined/classified as 'immediate early' or 'early', I think we can extrapolate to all other genes. For Inc genes, I entered data and made sparkline charts in excel a couple of weeks ago. Take a look. From my perspective, chart > raw data, but visual model > chart...
[Inc table.xlsx](https://github.com/SuLab/ChlamBase.org/files/1194821/Inc.table.xlsx)

**Comment by putmantime** [comment]
@andrewsu  I like the Candlestick charts but  I think the central issue that remains when we want to compare ortholog expression timing is how do we compare one number to the other when the hpi timepoints are different?  @khybiske I like the histograms, agree that visual model is most satisfying for a summary page of the gene like chlambase offers, but I think the central issue I mentioned requires a different model for each dataset at this point.  

Here is a very crude possible option where all timepoints are included so the viewer can see the overall trend across orthologs from, the raw data.   https://drive.google.com/file/d/0Bz6pVfjuj2bhZmRoeENuM0hTV0k/view?usp=sharing.  I still wonder about harmonizing the y-axis though.  I will do a deeper dive into the methods to see how those numbers were generated and if it is in anyway possible or appropriate to include them in the same chart.  We could then bin the stages visually on the chart (e.g. superimposed shaded columns that bin hpis 1-6 as early, 8-16 as mid, etc.)  

This may be getting too complicated to easily interpret though.

**Comment by andrewsu** [comment]
@khybiske assuming that the sparklines in excel qualify as "charts"?  If so, what do you envision for "visual models"?

@putmantime I absolutely think that it should be a different image (model?) for each data set...

I should also note that while having the discussion is great and should continue so we can converge on a design, I do think that @putmantime should focus whatever development time he has on tackling the issues tagged "high priority"...

**Comment by khybiske** [comment]
@andrewsu By visual models, I just meant what Tim has already done. Sorry for any confusion!

I fully agree that this issue is probably not the best use of Tim's time, and that there are higher priority items to knock off. Perhaps the simplest way to deal with this is to scrap trying to show expression data for ortholog strains. For example, we leave L2 as you have it, and just do something similar with the new data for Ctr D. The two datasets were generated quite differently, and I am not sure how well they even compare. Our mini analysis of Inc genes (excel file I sent) left me puzzled as to why numerous genes gave drastically different results. 

What do you guys think?

@putmantime if you go this route, then just devise a system for naming genes in Caldwell's set. We can leave it at that.

**Comment by andrewsu** [comment]
@khybiske so if I understand your proposal correctly, we show L2 expression data on L2 genes only, and show Ctr D expression data on Ctr D genes only.  Each data visualization (eg axis labels) would be tailored to its own data set, with no attempt to normalize.  If an end user wants to see expression data for the ortholog, then they click over to that page using the link in the ortholog module.  Is that correct?  If so, I'm supportive of that plan...

**Comment by khybiske** [comment]
@andrewsu Correct! And as a matter of personal preference, I like Tim's current approach of indicating expression times (early, mid, late, etc) rather than a graph or similar quantitative representation.

**Comment by putmantime** [comment]
Ok, so I will create a new model for the Ctr D data that uses it's own expression timing vocabulary, and the user can compare by clicking on the ortholog link between L2 and D.

**Comment by putmantime** [comment]
@andrewsu @khybiske  Here is my main issue with doing the same with the D (Belland) data as I did with the data for L2.  The L2 data from the original table you sent us was binned into the different groups by someone or an algorithm already (guessing it was the former).  Essentially a call was made that the numbers jumped at 3 hrs and stayed high so it was an Early.  Or the numbers stayed low until 16 hours and then jumped so it was a Mid_late etc.  The Belland table doesn't make that call.  It just reports the numbers.  So, it seems that I need to write an algorithm to do this for the D/Belland data?  If so, I just need to note that that isn't trivial, as thresholds have to be set, and all time points have to be included in decision making.

**Comment by khybiske** [comment]
Hmm, all of this sounds like a poor use of your finite time. What about simply putting in the code so that data entry is possible by users (i.e. us). Then when Scott and I attempt a data entry bonanza, we can make those calls with the Belland data and add entries to the site. Possible? 

The only issue I see is that your Expression Timing module is fixed – does not allow annotation addition.

Worst case, we just shelve the Ctr D data for a while.

**Comment by andrewsu** [comment]
>  So, it seems that I need to write an algorithm to do this for the D/Belland data? If so, I just need to note that that isn't trivial, as thresholds have to be set, and all time points have to be included in decision making.

I would definitely _not_ be in favor of crafting an ad hoc algorithm to try to cram the Belland data into something resembling the L2 data.  I think those should be treated as two completely independent data sets, and chlambase's presentation should be tailored to each.  L2 data was categorized, so the "tag" style marks we have are perfect.  Belland data is numeric, so presentation of that should be something more like a chart.  Yes, it means that we need two separate display widgets, but that I think is the right thing to do.  But the second chart-style widget is something that should be on someone else's plate (not Tim's), so along those lines I'm adding the "help-wanted" label here too...

my two cents...

**Comment by djow2019** [comment]
Do we still want a candlestick chart to display the caldwell data? I can get this loaded into chlambase for Ctr D.

**Comment by khybiske** [comment]
If not too challenging, then please do! Now that wikigenomes is expanding to new bugs, I can see this effort bearing fruit in the future (ie not be chlambase specific)

**Comment by djow2019** [comment]
Great, is the lnc.table spreadsheet the most up to date?
