### ISSUE TITLE
Move EB/RB to expression module

### ISSUE THREAD

**Issue by djow2019** [SuLab/WikiGenomesBase#164]

**Comment by djow2019** [comment]
@khybiske How would you like it displayed? Two columns one side reticulate timing another elementary? Two columns one side generic expression timing, other EB/RB?

**Comment by khybiske** [comment]
<img width="1160" alt="screen shot 2018-07-26 at 10 31 32 am" src="https://user-images.githubusercontent.com/29986637/43278158-1990664c-90bf-11e8-8066-7f2b79922c4b.png">

**Comment by khybiske** [comment]
Something like this? Or, given all the whitespace, you could put mRNA as a left column, and RB/EB as a right column

**Comment by khybiske** [comment]
Note: I did multiple lines as an example for when 2 datasets may disagree.

**Comment by djow2019** [comment]
Would the mRNA column be used to display the quantitative data?

**Comment by djow2019** [comment]
I could also easily fit it in a single row, and maybe instead of a button for EB_and_RB, highlight both EB and RB individually

**Comment by khybiske** [comment]
mRNA is my shorthand for the RB expression timing (what's currently there)

**Comment by djow2019** [comment]
Actually, if we are going to use multiple data sets to display EB/RB information, then I don't think we can use WikiData to store this information.

Thoughts @andrewsu ?

**Comment by khybiske** [comment]
It's a little apples and oranges, but the current module shows mRNA expression (microarray, although RNAseq data will be coming along soon). The RB/EB conveys which form the protein is found to be made in.

**Comment by djow2019** [comment]
What do you think of this
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/1b451a9b-d925-4d90-ac3b-b3de263cd842)

**Comment by khybiske** [comment]
Looks perfect to me. Does 'add annotation' allow for both columns? or just RB/EB?

**Comment by djow2019** [comment]
Changed the dropdown to include EB/RB/Both
