### ISSUE TITLE
revision history module

### ISSUE THREAD

**Issue by djow2019** [SuLab/WikiGenomesBase#169]
I'm having a lot of issues with making batch requests for a set of genes, but it is very easy to query the revision history for a single gene. I'm proposing that instead of a broad organism feedback, we can have a "revision history" module at the bottom of each gene page. Thoughts @andrewsu @khybiske ?

**Comment by andrewsu** [comment]
I think that is also a useful feature, but because we expect edits on any particular gene to be relatively infrequent, it is useful to *also* have a site/strain/organism-wide revision history feed.  

Can you outline the batch request issues you're seeing?

**Comment by khybiske** [comment]
Hard for me to comment, I don't fully get what 'batch requests' means for CB (forgive me). But I do like the idea of a revision history display – a lot.

**Comment by djow2019** [comment]
It is still with the PBB tracker. Will talk to Greg again to see if I can get it to work.

**Comment by djow2019** [comment]
We can definitely have both, and in fact since the organism-wide feed might take some time, I can implement the revision history module as well
