### ISSUE TITLE
Ortholog alignment coloring

### ISSUE THREAD

**Issue by khybiske** [SuLab/WikiGenomesBase#171]
@djow2019 This is minor, but is there any way to change the coloring scheme of DNA and amino acid alignments? There are a variety of schemes out there, and everyone has their own preferences... I think the most useful for this module is one where contrast or color was used to highlight divergent bases/amino acids. As opposed to coloring everything. Again, minor...

**Comment by djow2019** [comment]
I don't think the MSA viewer supports coloring divergent bases. It uses a static color scheme that gives every base a unique color. I can, however, give you the option to select a colorscheme that you would prefer. I'll re-enable the options bar so we can play around with it.

**Comment by djow2019** [comment]
What about something like this
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/37ce2b01-857a-4f79-a5a1-bf7081c9e63a)

Msa viewer gives the user a menu at the top to dynamically change the color scheme, but for some reason it isn't working (just unresponsive). So we can add the conserved sequences at the top instead.

Check out their example here http://workmen.biojs.net/demo/msa/fer1_annoted and let me know if there is a color scheme that you would prefer. That menu that is shown at the top does not seem to work in chlambase.

**Comment by khybiske** [comment]
I like Clustal2 the best, in case it is possible to change. I don't like the stacked letter thing at the top (I never like those).

**Comment by djow2019** [comment]
Changes now live. You can further tweak the display with the option bar now.

**Comment by khybiske** [comment]
Outstanding!
