### ISSUE TITLE
User instructions for alias editing

### ISSUE THREAD

**Issue by khybiske** [SuLab/WikiGenomesBase#181]
@djow2019 thinking more about this... What might be helpful (and easy) is if you wrote a brief set of  instructions inside the annotation wizard, so that users know what we'd like them to type in the alias box (or what's allowable). Or maybe provide examples? I am on board with following NCBI's naming... but that also seems very inconsistent. There are L2 genes that contain abbreviated names (ie CTL0006), and those that don't (CTL0245, which we discussed yesterday).

**Comment by khybiske** [comment]
I do find it off-putting that the abbreviated gene names (in the CTL0245 example) are practically buried as small-type aliases, when that's really the most important descriptor after the locus tag. 
To even find this gene (L2 ortholog), I search for 'glgb', click the Cpn ortholog search result (it's the only one that comes up), then click CTL0245 in the ortholog table. Not ideal, ya?

**Comment by djow2019** [comment]
I think that the best way to address this might be to make a new wikidata property called "abbreviated name" and we manually add all the abbreviated names as a property of each gene

**Comment by khybiske** [comment]
I'd love that.

**Comment by djow2019** [comment]
@khybiske do you have a table mapping locus tags to abbreviated names? Sadly, NCBI does not contain any structured form for abbreviated names, so we will have to create a spreadsheet ourselves.

**Comment by khybiske** [comment]
Shared a google sheet with you.

**Comment by djow2019** [comment]
Perfect!

**Comment by djow2019** [comment]
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/90142969-9c95-4341-b1ab-dc8a7e24a904)

Just about done here. Will also display the gene symbol in the overview panel. All thats left is to get the remaining symbols in WD

**Comment by djow2019** [comment]
Since we have a form for editing gene symbols, and that aliases, as a separate form, do not require any special naming conventions, I am marking this as resolved.
