### ISSUE TITLE
Add PDB entries

### ISSUE THREAD

**Issue by putmantime** [SuLab/WikiGenomesBase#22]
-possible issues  in identifier mapping with PDB and Uniprot/NCBI

**Comment by djow2019** [comment]
From today's meeting:
@khybiske provide sample data in a google sheet mapping chlamydia proteins to PDB IDs
Then I can put them in WikiData, then make the corresponding interface

**Comment by khybiske** [comment]
@djow2019 Shared a google sheet link with you. If any issues accessing, or with the data, let me know!

**Comment by djow2019** [comment]
@khybiske what references do you have for assigning the PDB IDs?

**Comment by khybiske** [comment]
@djow2019 I am not a big structure guy to know what is most pertinent to capture. Resolution perhaps (in angstroms)? One of our consultant friends has solved a bunch of our CT structures, so once you get it live on the dev site, I can ask him for comments.

**Comment by khybiske** [comment]
Re: Refs, is it possible to put a link to PDB? Really, we are just grabbing their data. I wouldn't want this module to be user-curated. I mean, yes, but only in asking users to point the gene page to the proper PDB page. How are you implementing this?

**Comment by djow2019** [comment]
Right now I don't plan on adding an annotation form for PDB structures. I can turn the ID into a hyperlink to the proper PDB page

**Comment by khybiske** [comment]
That's good for now. I'll reserve any further comments until an example is live.

**Comment by djow2019** [comment]
Its live now

**Comment by djow2019** [comment]
Revisiting the references needed for the PDB Ids. I added a few columns to the spreadsheet that should be filled out if possible. Right now they don't have any sort of information to authenticate the data so it might be removed at some point unless we put something in.

**Comment by khybiske** [comment]
@djow2019 Sheet filled.

**Comment by khybiske** [comment]
I might suggest you put the PDB ID in the Gene Product module. And create an 'add annotation' function so that users can add new ones. Our collaborator Scott has solved ~10 of the Ct structures (half of those that exist), and he is personally eager to enter these into CB.

**Comment by djow2019** [comment]
Note: when creating annotation form also push image file
ex. https://www.ebi.ac.uk/pdbe/static/entry/5kbc_deposited_chain_front_image-800x800.png
