### ISSUE TITLE
Advanced searching

### ISSUE THREAD

**Issue by khybiske** [SuLab/WikiGenomesBase#80]
Let users search by multiple data fields. Another useful feature to add, should be easy.. 

Example:
Genome = C. trachomatis 434/Bu
Cellular component = inclusion membrane protein
Host-pathogen interaction = true (has an entry)

Very powerful and useful if we can do that.

**Comment by khybiske** [comment]
This is the same as

**Comment by khybiske** [comment]
Oops, this issue already exists as #16

**Comment by djow2019** [comment]
Here is what I have for UI:
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/8b9b2b1f-5df4-4176-b6a2-f432df11d1a7)
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/200e77ef-0835-4b59-8d24-0882e88e1320)

Currently will have options for any of the 3 go classes, HP, uniprot and entrez

**Comment by djow2019** [comment]
Latest Update
![image.png](https://images.zenhubusercontent.com/5a6639ad4b5806bc2bc3ca25/6e3fa79b-c406-462b-a95f-1bc207f4b690)

**Comment by djow2019** [comment]
@andrewsu @khybiske Live on chlambase dev. https://dev.chlambase.org/keyword/test

**Comment by djow2019** [comment]
TODO: Add autocomplete for go term fields

**Comment by djow2019** [comment]
TODO: Add mutant (after refactoring) and EC Number search fields

**Comment by djow2019** [comment]
All done, but leaving open until we move to production

**Comment by khybiske** [comment]
2 small suggestions:
1. Can you add an advanced search link to the header bar of all gene pages?
2. (not a small one) Give thought to adding an option for ortholog filtering. I'll think about this as well... but an example use case: filter all Cmur genes for those with no orthologs in CT-D and CT-L2. No bright idea how to implement this in a simple way.
